Layout/LineLength:
  Max: 200

Metrics/BlockLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9
